---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Platform"
subtitle: "Apps"
logo: 'https://www.visaonoticias.com/userfiles/images/1-Captura%20de%20tela%20inteira%2001032021%20181603.jpg'
# icon: "faas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Criado por Rhaniel & Gustavo'

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#FF6400"
    highlight-secondary: "#000000"
    highlight-hover: "#000000"
    background: "##000000"
    card-background: "#000000"
    text: "#ffffff"
    text-header: "#ffffff"
    text-title: "#ffffff"
    text-subtitle: "#ffffff"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#ffffff"
    link-hover: "#ffffff"
  dark:
    highlight-primary: "#FF6400"
    highlight-secondary: "#000000"
    highlight-hover: "#000000"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

#Apps
services:
  - name: "Cloud"
    icon: "fas fa-cloud"
    items:
      - name: "AWS - Console"
        logo: 'https://static-00.iconduck.com/assets.00/aws-icon-2048x2048-274bm1xi.png'
        subtitle: "Account manager"
        tag: "app"
        keywords: "Account manager"
        url: "https://bildvitta.awsapps.com/start#/"
        target: "_blank" # optional html a tag target attribute
      - name: "Azure - Console"
        logo: 'https://www.01it.com.br/uploads/img/servicos/13/4cc1c3c7962898e47c289d0f64eadb53.png'
        subtitle: "Account manager"
        tag: "app"
        url: "https://portal.azure.com/#home"
      - name: "Oracle - Console"
        logo: 'https://static-00.iconduck.com/assets.00/oracle-cloud-icon-2048x1291-i8p6hb32.png'
        subtitle: "Account manager"
        tag: "app"
        url: "https://console.sa-saopaulo-1.oraclecloud.com/"


  - name: "Monitoring"
    icon: "fas fa-cloud"
    items:
      - name: "Skyone"
        logo: "https://www.site24x7.com/app/cus_image?user_id=spwRXUhOTc2Ro48Cu7flz3n55AWP_CwxXRw10CKThuvSSeF2m8avybiROB2PtNEVB0CwfuX6Z_QjWTukbXMh4JoVCdtL12R6Sz5Z6CYYy7jK01ZvF1kx6pwpU0xZAGzu"
        subtitle: "Monitoring Status"
        tag: "app"
        url: "https://sre.skyone.guru/app/login/bild"

      - name: "BI"
        logo: "https://img.site24x7static.com/images/site24x7-logo-web.png"
        subtitle: "Monitoring BI"
        tag: "app"
        url: "https://www.site24x7.com/public/dashboard/CkEcCmRjTGtZOx0tFLMLdQ0zATVRotnceHgR6rp5BJyBi08gwLH5PooKxKUWiiz0zMN5-bq7FQmL7qi__FL3VuTz5vhdT-dnzQI3vIJ-LPJDTfS_0lnBe_g4lMCkrCHj"

      - name: "Mega"
        logo: "https://img.site24x7static.com/images/site24x7-logo-web.png"
        subtitle: "Monitoring Mega"
        tag: "app"
        url: "https://www.site24x7.com/public/dashboard/uRrUyVf-_6bUDgP-GpK2UK63Gbc6JKk1WXjx7y5VypaBi08gwLH5PooKxKUWiiz0zMN5-bq7FQmL7qi__FL3Vki_vAe_Mhl9dsMVnwVs7LEjQZ6P9_Bl9nEkFDsy_Ewx"

      - name: "Robot"
        logo: "https://img.site24x7static.com/images/site24x7-logo-web.png"
        subtitle: "Monitoring Robot"
        tag: "app"
        url: "https://www.site24x7.com/public/dashboard/1WSKt8WyLOlW0F-nIi_AzSmiwJh4IaQoqoCeCBOUIMCBi08gwLH5PooKxKUWiiz0zMN5-bq7FQmL7qi__FL3Viplfiup4rUKHHdwLqQzD3DXe5OAYwy_XxJqwBUV7V6P"

  - name: "DevOps Framework"
    icon: "fas fa-cloud"
    items:
      - name: "FinOps"
        logo: "https://miro.medium.com/v2/resize:fit:600/0*gr_HuxOPK_QqGRJ4.png"
        subtitle: "Data-Driven Spending"
        tag: "app"
        url: "https://almee.painel.cloud"

      - name: "Terraform"
        logo: "https://static-00.iconduck.com/assets.00/terraform-icon-1803x2048-hodrzd3t.png"
        subtitle: "Backend infrastructure"
        tag: "app"
        url: "https://app.terraform.io/" 

      - name: "Github"
        logo: "https://icon-library.com/images/github-icon-white/github-icon-white-6.jpg"
        subtitle: "Repositories"
        tag: "app"
        url: "https://github.com/BildSustentacao?q=&type=all&language=&sort=" 


      - name: "1Password"
        logo: "https://upload.wikimedia.org/wikipedia/commons/5/5b/1Password_icon.png"
        subtitle: "Another application"
        tag: "app"
        url: "https://bildvitta.1password.com/home"  
        
      - name: "Whimsical"
        logo: "https://whimsical.com/s/images/apple-touch-icon-180_df3b1343f6670c1fe2d90b1e1425bb08.png"
        subtitle: "Infrastructure architecture design"
        tag: "app"
        url: "https://whimsical.com/" 

      - name: "Diagrams"
        logo: "https://seeklogo.com/images/D/draw-io-logo-59133ABE5E-seeklogo.com.png"
        subtitle: "Infrastructure architecture design"
        tag: "app"
        url: "https://app.diagrams.net/" 

      - name: "Gitmind"
        logo: "https://www.eastersealstech.com/wp-content/uploads/2023/05/gitmind-app-logo.png"
        subtitle: "Infrastructure architecture design"
        tag: "app"
        url: "https://gitmind.com/" 
        
      - name: "Cloudcraft"
        logo: "https://cdn.freebiesupply.com/logos/large/2x/cloudcraft-logo-png-transparent.png"
        subtitle: "Infrastructure architecture design"
        tag: "app"
        url: "https://app.cloudcraft.co/" 

      - name: "Locust"
        logo: "https://locust.bildcloud.com.br/static/img/logo.png?v=2.15.1"
        subtitle: "Infrastructure architecture tester"
        tag: "app"
        url: "https://locust.bildcloud.com.br/" 

      - name: "ArgoCD"
        logo: "https://icon.icepanel.io/Technology/svg/Argo-CD.svg"
        subtitle: "CICD architecture Deploy"
        tag: "app"
        url: "https://argocd.bildcloud.com.br/" 

      - name: "Rancher"
        logo: "https://icon.icepanel.io/Technology/svg/Rancher.svg"
        subtitle: "Connect Infrastructure Clusters EKS"
        tag: "app"
        url: "https://rancher.almee.com.br/" 


  - name: "Help Desk"
    icon: "fas fa-cloud"
    items:
      - name: "TI Bild"
        logo: "https://images.assets-landingi.com/kuB5Li1XpP6HyhNM/logo_cor_brnaco.jpg"
        subtitle: "TI Almee Painel HelpDesk"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://ti.bild.com.br"
        target: "_blank" # optional html a tag target attribute
        
      - name: "Dashboard Skyone"
        logo: "https://www.site24x7.com/app/cus_image?user_id=spwRXUhOTc2Ro48Cu7flz3n55AWP_CwxXRw10CKThuvSSeF2m8avybiROB2PtNEVB0CwfuX6Z_QjWTukbXMh4JoVCdtL12R6Sz5Z6CYYy7jK01ZvF1kx6pwpU0xZAGzu"
        subtitle: "Skyone Painel HelpDesk"
        tag: "app"
        url: "https://portal.skyone.cloud/dashboard"

      - name: "Bitly"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Bit.ly_Logo.svg/2560px-Bit.ly_Logo.svg.png"
        subtitle: "Dashboard Painel HelpDesk"
        tag: "app"
        url: "https://bitly.com/a/sign_in?rd=/Bkbodul2wmD/bitlinks/"             

        
        
                
